# alice(172.28.0.3) <-> (172.28.0.2)moon(172.30.0.2) -> internet
version: "3.3"

services:
  alice:
    container_name: alice
    image: ubuntu-with-tools
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    volumes:
      - cert-volume:/etc/ssl/certs #:ro # Mount as read-only
    hostname: alice
    networks:
      moon-internal:
        ipv4_address: 172.28.0.3
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.28.0.2 &&
      tail -f /dev/null"

  moon: # http://localhost:8082/#/flows
    container_name: moon
    # image: mitmproxy/mitmproxy  # Using the official mitmproxy ima  ge
    build:
      context: .
      dockerfile: Dockerfile.mitmproxy
      args: # https://mitmproxy.org/downloads/#10.2.4/
        - MITMPROXY_WHEEL=mitmproxy-10.2.4-py3-none-any.whl
    cap_add:
      - NET_ADMIN
    hostname: moon
    volumes:
      - cert-volume:/root/.mitmproxy
    networks:
      moon-internal:
        ipv4_address: 172.28.0.2
      internet:
        ipv4_address: 172.30.0.2
    ports:
      - "8080:8080"  # Expose the mitmproxy web interface port to the host
      - "8081:8081" 
    tty: true
    stdin_open: true
    # https://docs.mitmproxy.org/stable/concepts-modes/#upstream-proxy
    command: mitmweb --web-host 0.0.0.0 --web-port 8081 --mode transparent --showhost --ssl-insecure
    expose:
        - "8080"
        - "8081"

networks:
  moon-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  cert-volume:
